# Generated by Django 5.1.6 on 2025-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='teacher',
            new_name='student',
        ),
    ]
