# Generated by Django 5.2.4 on 2025-08-14 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0003_students_parent_first_name_students_parent_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название класса')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс (1-11)')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год (например: 2024-2025)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.RemoveField(
            model_name='students',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия родителя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона родителя'),
        ),
        migrations.AddField(
            model_name='students',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mental_app.class', verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль учителя',
                'verbose_name_plural': 'Профили учителей',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='mental_app.teacherprofile', verbose_name='Учитель'),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'teacher', 'academic_year')},
        ),
    ]
