# Generated by Django 5.2.4 on 2025-08-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0004_class_remove_students_student_alter_students_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(help_text='Например: 2024-2025, 2024/2025, 2024', max_length=20, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Например: "А", "Б", "В", "1А", "2Б", "Математический", "Гуманитарный"', max_length=100, verbose_name='Название класса'),
        ),
    ]
