# Generated by Django 5.2.4 on 2025-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0005_alter_class_academic_year_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.CharField(default='Понедельник', help_text='Например: "Пн, Ср, Пт" или "Вторник, Четверг"', max_length=100, verbose_name='Дни занятий'),
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.TimeField(default='09:00', help_text='Время начала занятий', verbose_name='Время занятий'),
        ),
    ]
