# Generated by Django 5.2.4 on 2025-08-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0006_remove_class_grade_class_days_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days',
            field=models.CharField(help_text='Например: "Пн, Ср, Пт" или "Вторник, Четверг"', max_length=100, verbose_name='Дни занятий'),
        ),
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.TimeField(help_text='Время начала занятий', verbose_name='Время занятий'),
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='mental_app.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Аккаунт ученика',
                'verbose_name_plural': 'Аккаунты учеников',
            },
        ),
    ]
