# Generated by Django 5.2.4 on 2025-08-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0007_alter_class_days_alter_class_time_studentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='mental_app.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
