# Generated by Django 5.2.4 on 2025-08-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0008_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_lesson', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за занятие (руб.)')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за месяц (руб.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('class_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='mental_app.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Настройка оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mental_app.class', verbose_name='Класс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mental_app.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-date', 'student__surname', 'student__name'],
                'unique_together': {('student', 'date', 'class_group')},
            },
        ),
    ]
