# Generated by Django 5.2.4 on 2025-08-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0009_paymentsettings_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='payment_carried_over',
            field=models.BooleanField(default=False, verbose_name='Оплата перенесена на следующий месяц'),
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='mental_app.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Месячное расписание',
                'verbose_name_plural': 'Месячные расписания',
                'ordering': ['-year', '-month'],
                'unique_together': {('class_group', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='monthly_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mental_app.monthlyschedule', verbose_name='Месячное расписание'),
        ),
    ]
