# Generated by Django 5.2.4 on 2025-08-15 07:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0010_attendance_payment_carried_over_monthlyschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': 'Настройки оплаты', 'verbose_name_plural': 'Настройки оплаты'},
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='price_per_lesson',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Ежемесячная плата'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_day',
            field=models.IntegerField(default=15, help_text='День месяца, когда должна производиться оплата', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ClassGameAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('multiplication_choose', 'Умножение'), ('square', 'Квадраты'), ('tricks', 'Трюки'), ('flashcards', 'Флэшкарты'), ('multiplication_base', 'Умножение от базы'), ('multiplication_to_20', 'Умножение до 20')], max_length=50, verbose_name='Игра')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_access', to='mental_app.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Доступность игры для класса',
                'verbose_name_plural': 'Доступность игр для классов',
                'unique_together': {('class_group', 'game')},
            },
        ),
    ]
