# Generated by Django 5.2.4 on 2025-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0012_gamesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='lesson_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена за занятие'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_type',
            field=models.CharField(choices=[('per_lesson', 'За каждое занятие'), ('monthly', 'Ежемесячно'), ('mixed', 'Смешанная (месячная + за занятия)')], default='per_lesson', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
