# Generated by Django 5.2.4 on 2025-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0013_paymentsettings_lesson_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='lesson_fee',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='class',
            name='lesson_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Стоимость одного занятия в рублях', max_digits=8, verbose_name='Стоимость за занятие'),
        ),
    ]
