# Generated by Django 5.2.4 on 2025-08-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0014_remove_paymentsettings_lesson_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='monthly_fee',
        ),
    ]
