# Generated by Django 5.2.4 on 2025-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0015_remove_paymentsettings_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgameaccess',
            name='game',
            field=models.CharField(choices=[('multiplication_choose', 'Умножение'), ('square', 'Квадраты'), ('tricks', 'Трюки'), ('flashcards', 'Флэшкарты'), ('multiplication_base', 'Умножение от базы'), ('multiplication_to_20', 'Умножение до 20'), ('brothers', 'Братья'), ('friends', 'Друзья'), ('friend_brother', 'Друг+брат'), ('multiplication_table', 'Таблица умножения')], max_length=50, verbose_name='Игра'),
        ),
    ]
