# Generated by Django 5.2.7 on 2025-10-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0016_alter_classgameaccess_game'),
    ]

    operations = [
        # Добавляем индексы для оптимизации производительности
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_students_class_id ON mental_app_students(student_class_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_students_class_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_attendance_date ON mental_app_attendance(date);",
            reverse_sql="DROP INDEX IF EXISTS idx_attendance_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON mental_app_attendance(student_id, date);",
            reverse_sql="DROP INDEX IF EXISTS idx_attendance_student_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_attendance_class_date ON mental_app_attendance(class_group_id, date);",
            reverse_sql="DROP INDEX IF EXISTS idx_attendance_class_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_homework_class_active ON mental_app_homework(class_group_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_homework_class_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_class_teacher ON mental_app_class(teacher_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_class_teacher;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_monthlysch_class_date ON mental_app_monthlyschedule(class_group_id, year, month);",
            reverse_sql="DROP INDEX IF EXISTS idx_monthlysch_class_date;"
        ),
    ]
